# Example docker-compose.yml for running both services
version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/src:/app/src # Mount source for development
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true # For Hot Reloading in Docker
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend/src:/app/src # Mount source for development
